// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnw5SJ1G-0by4rsX5RIBmcqELV9MdBCnY',
    appId: '1:1031183302428:web:3de658e61752db571c04d9',
    messagingSenderId: '1031183302428',
    projectId: 'slotseek-9f892',
    authDomain: 'slotseek-9f892.firebaseapp.com',
    storageBucket: 'slotseek-9f892.appspot.com',
    measurementId: 'G-M4SFWG5TLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk0Ddp9AaTmNglRQsc6JeXUrzIbYtvTrU',
    appId: '1:1031183302428:android:d6a3fe675f8a01181c04d9',
    messagingSenderId: '1031183302428',
    projectId: 'slotseek-9f892',
    storageBucket: 'slotseek-9f892.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXchM12ujOD-w59pP1HVqPDNt3w30xsw4',
    appId: '1:1031183302428:ios:91c987782ae394f21c04d9',
    messagingSenderId: '1031183302428',
    projectId: 'slotseek-9f892',
    storageBucket: 'slotseek-9f892.appspot.com',
    iosClientId: '1031183302428-55egtpe0dej8q74o56n01gddh1bm2q0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.slotSeek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXchM12ujOD-w59pP1HVqPDNt3w30xsw4',
    appId: '1:1031183302428:ios:91c987782ae394f21c04d9',
    messagingSenderId: '1031183302428',
    projectId: 'slotseek-9f892',
    storageBucket: 'slotseek-9f892.appspot.com',
    iosClientId: '1031183302428-55egtpe0dej8q74o56n01gddh1bm2q0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.slotSeek',
  );
}
